// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"encoding/json"
	"time"
)

type Block struct {
	ChainNum int16
	Height   int64
	Data     json.RawMessage
	Time     time.Time
}

type Chain struct {
	Num     int16
	ChainID string
}

type Msg struct {
	ChainNum    int16
	BlockHeight int64
	TxIdx       int16
	MsgIdx      int16
	Data        json.RawMessage
}

type MsgEvent struct {
	ChainNum    int16
	BlockHeight int64
	TxIdx       int16
	MsgIdx      int16
	Type        string
}

type MsgEventAttr struct {
	ChainNum    int16
	BlockHeight int64
	TxIdx       int16
	MsgIdx      int16
	Type        string
	Key         string
	Value       string
	ValueHash   []byte
}

type Tx struct {
	ChainNum    int16
	BlockHeight int64
	TxIdx       int16
	Hash        []byte
	Data        json.RawMessage
}
