// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: reader.sql

package db

import (
	"context"
)

const getChain = `-- name: GetChain :one
SELECT num, chain_id FROM chain WHERE chain_id=$1
`

func (q *Queries) GetChain(ctx context.Context, chainID string) (Chain, error) {
	row := q.db.QueryRowContext(ctx, getChain, chainID)
	var i Chain
	err := row.Scan(&i.Num, &i.ChainID)
	return i, err
}
